#!/usr/bin/env node

/**
 * Script para gerar config.js a partir de variáveis de ambiente
 * Usado durante o build no Netlify
 */

const fs = require('fs');
const path = require('path');

// Valores padrão (fallback para desenvolvimento local)
const config = {
  supabaseUrl: process.env.SUPABASE_URL || 'https://bxvlfxawfwfqgsyipgyr.supabase.co',
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dmxmeGF3ZndmcWdzeWlwZ3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTkzODIsImV4cCI6MjA3ODA5NTM4Mn0.mNVK3WlTuTqT82RK8C922dTpTvE_WYGBI4EJUoGzY0g',
  seedRemote: false,
  hiddenPostIds: [],
  hiddenPostTitles: [],
  publisherServiceUrl: process.env.PUBLISHER_SERVICE_URL || '',
  publisherServiceToken: process.env.PUBLISHER_SERVICE_TOKEN || '',
  publisherAccounts: {
    PAULO: {
      email: process.env.PAULO_EMAIL || 'pvolker@mdh-hability.com',
      displayName: 'Paulo',
    },
    ANGELICA: {
      email: process.env.ANGELICA_EMAIL || 'angelica@lacasacreativa.net',
      displayName: 'Angelica',
    },
  },
  endpoints: {
    posts: '/posts',
    feedback: '/feedback',
    likes: '/likes',
    backup: '/backup',
  },
  enableSharedLikes: false,
};

// Gerar o conteúdo do arquivo config.js
const configContent = `/**
 * Configuration for Supabase connection
 * Generated automatically during build
 * DO NOT EDIT THIS FILE MANUALLY
 */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

// Escrever o arquivo
const outputPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outputPath, configContent, 'utf8');

console.log('✅ config.js gerado com sucesso!');
console.log('📍 Local:', outputPath);
